#!/usr/bin/env ruby

require './calculator.rb'

puts "Calculator treats numbers after new lines or commas as separate addends"
if ARGV.length < 1
  puts 'Usage: calculate "1,2,3..."'
else
	numbers = ARGV[0].dup
  calculator = Calculator.new
  puts "Total: #{calculator.add(numbers)}"
end
